#!/usr/bin/env python3
"""
Generate the CORDIC arctangent table.

Entry i is atan(2^-i) expressed in binary angular measure, where a full turn
is 2^16. The table is committed so the build never depends on Python.

Usage:
    python3 tools/gen_cordic_table.py > src/cordic_table.c
"""

import math
import sys

ITERATIONS = 15


def main():
    table = [round(math.atan(2.0 ** -i) / math.pi * 32768.0) for i in range(ITERATIONS)]

    # CORDIC gain: the vectoring rotation stretches the vector by this factor,
    # so magnitude has to be scaled back by its reciprocal.
    gain = 1.0
    for i in range(ITERATIONS):
        gain *= math.sqrt(1.0 + 4.0 ** -i)
    inv_gain_q15 = round(32768.0 / gain)

    print("/* Generated by tools/gen_cordic_table.py - do not edit by hand. */")
    print('#include "qcsi/phase.h"')
    print()
    print("/* atan(2^-i) in binary angular measure (full turn = 2^16). */")
    print(f"const int32_t qcsi_cordic_atan[{ITERATIONS}] = {{")
    for i, v in enumerate(table):
        print(f"    {v:6d},  /* atan(2^-{i}) = {math.degrees(math.atan(2.0**-i)):9.5f} deg */")
    print("};")
    print()
    print(f"/* 1 / {gain:.9f}, in Q15. */")
    print(f"const int32_t qcsi_cordic_inv_gain = {inv_gain_q15};")

    print(f"[info] CORDIC gain {gain:.9f}, inverse {inv_gain_q15} (Q15)",
          file=sys.stderr)
    print(f"[info] smallest angle step {table[-1]} BAM = "
          f"{table[-1] / 32768.0 * 180.0:.5f} deg", file=sys.stderr)


if __name__ == "__main__":
    main()
