#!/usr/bin/env python3
"""
Generate the CORDIC arctangent table.

Entry i is atan(2^-i) expressed in binary angular measure, where a full turn
is 2^16. The table is committed so the build never depends on Python.

The iteration count is read from include/qcsi/phase.h rather than repeated
here, and the generated file declares the array with the same macro. That
leaves one copy of the constant: raising QCSI_CORDIC_ITERATIONS and forgetting
to regenerate used to produce an array whose size disagreed with the extern
declaration in src/phase.c, which neither the compiler nor the linker
diagnoses. The generated static assertion catches the remaining case, a table
regenerated from a stale checkout, at compile time.

Usage:
    python3 tools/gen_cordic_table.py > src/cordic_table.c
"""

import math
import os
import re
import sys

HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      os.pardir, "include", "qcsi", "phase.h")


def read_iterations(path=HEADER):
    """Read QCSI_CORDIC_ITERATIONS from the public header."""
    with open(path) as f:
        m = re.search(r"^#define\s+QCSI_CORDIC_ITERATIONS\s+(\d+)\s*$",
                      f.read(), re.MULTILINE)
    if m is None:
        raise SystemExit(f"QCSI_CORDIC_ITERATIONS not found in {path}")
    return int(m.group(1))


def main():
    iterations = read_iterations()
    table = [round(math.atan(2.0 ** -i) / math.pi * 32768.0) for i in range(iterations)]

    # CORDIC gain: the vectoring rotation stretches the vector by this factor,
    # so magnitude has to be scaled back by its reciprocal.
    gain = 1.0
    for i in range(iterations):
        gain *= math.sqrt(1.0 + 4.0 ** -i)
    inv_gain_q15 = round(32768.0 / gain)

    print("/* Generated by tools/gen_cordic_table.py - do not edit by hand. */")
    print('#include "qcsi/phase.h"')
    print()
    print("/* Entries written by the generator. If this disagrees with the")
    print("   header's iteration count the table is stale: the array below")
    print("   would be silently zero-padded, so it is refused at compile")
    print("   time instead. */")
    print(f"#define QCSI_CORDIC_TABLE_ENTRIES {iterations}")
    print("typedef char qcsi_cordic_table_matches_header[")
    print("    (QCSI_CORDIC_TABLE_ENTRIES == QCSI_CORDIC_ITERATIONS) ? 1 : -1];")
    print()
    print("/* atan(2^-i) in binary angular measure (full turn = 2^16). */")
    print("const int32_t qcsi_cordic_atan[QCSI_CORDIC_ITERATIONS] = {")
    for i, v in enumerate(table):
        print(f"    {v:6d},  /* atan(2^-{i}) = {math.degrees(math.atan(2.0**-i)):9.5f} deg */")
    print("};")
    print()
    print(f"/* 1 / {gain:.9f}, in Q15. */")
    print(f"const int32_t qcsi_cordic_inv_gain = {inv_gain_q15};")

    print(f"[info] {iterations} iterations, read from include/qcsi/phase.h",
          file=sys.stderr)
    print(f"[info] CORDIC gain {gain:.9f}, inverse {inv_gain_q15} (Q15)",
          file=sys.stderr)
    print(f"[info] smallest angle step {table[-1]} BAM = "
          f"{table[-1] / 32768.0 * 180.0:.5f} deg", file=sys.stderr)


if __name__ == "__main__":
    main()
