/* Generated by tools/gen_cordic_table.py - do not edit by hand. */
#include "qcsi/phase.h"

/* Entries written by the generator. If this disagrees with the
   header's iteration count the table is stale: the array below
   would be silently zero-padded, so it is refused at compile
   time instead. */
#define QCSI_CORDIC_TABLE_ENTRIES 15
typedef char qcsi_cordic_table_matches_header[
    (QCSI_CORDIC_TABLE_ENTRIES == QCSI_CORDIC_ITERATIONS) ? 1 : -1];

/* atan(2^-i) in binary angular measure (full turn = 2^16). */
const int32_t qcsi_cordic_atan[QCSI_CORDIC_ITERATIONS] = {
      8192,  /* atan(2^-0) =  45.00000 deg */
      4836,  /* atan(2^-1) =  26.56505 deg */
      2555,  /* atan(2^-2) =  14.03624 deg */
      1297,  /* atan(2^-3) =   7.12502 deg */
       651,  /* atan(2^-4) =   3.57633 deg */
       326,  /* atan(2^-5) =   1.78991 deg */
       163,  /* atan(2^-6) =   0.89517 deg */
        81,  /* atan(2^-7) =   0.44761 deg */
        41,  /* atan(2^-8) =   0.22381 deg */
        20,  /* atan(2^-9) =   0.11191 deg */
        10,  /* atan(2^-10) =   0.05595 deg */
         5,  /* atan(2^-11) =   0.02798 deg */
         3,  /* atan(2^-12) =   0.01399 deg */
         1,  /* atan(2^-13) =   0.00699 deg */
         1,  /* atan(2^-14) =   0.00350 deg */
};

/* 1 / 1.646760257, in Q15. */
const int32_t qcsi_cordic_inv_gain = 19898;
